name: Generate Syntax Collapse Log

on:
  schedule:
    - cron: "0 21,1,5,9,13 * * *"  # JST 6,10,14,18,22
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install openai==0.28

      - name: Generate syntax collapse log
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python generate_collapse_log.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add log*.md README.md
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Auto: Generate new syntax collapse log"
            git push
          fi
