name: Generate Syntax Collapse Log

on:
  schedule:
    - cron: "0 1,5,9 * * *"  # JST 10,14,18（3回/日）
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install openai==0.28

      - name: Generate syntax collapse log
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python generate_collapse_log.py

      - name: Commit and push changes using PAT
        env:
          PAT_FOR_PUSH: ${{ secrets.PAT_FOR_PUSH }}
        run: |
          git config --global user.name 'autobot'
          git config --global user.email 'autobot@example.com'

          # PATを使ってpush認証設定
          git remote set-url origin https://x-access-token:${PAT_FOR_PUSH}@github.com/${{ github.repository }}

          # ステージング対象
          find logs -name "*.md" -exec git add {} +
          find summaries/note -name "*.md" -exec git add {} + || true
          find summaries/zine -name "*.md" -exec git add {} + || true
          git add README.md || true

          CHANGES=$(git diff --cached --name-only)
          if [ -z "$CHANGES" ]; then
            echo "No changes to commit."
          else
            git commit -m "Auto: Generate new syntax collapse log and summaries"
            git push origin HEAD
          fi
