name: Trigger Death from Workflow Run

on:
  workflow_run:
    workflows: ["Generate Syntax Collapse Log"]
    types:
      - completed

jobs:
  post-via-import:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Poetic-Syntax-Collapse-Archive
        uses: actions/checkout@v3

      - name: Get latest log file
        id: get_log
        run: |
          LATEST=$(ls logs | grep -E '^log[0-9]+\.md$' | sort | tail -n 1)
          echo "latest_log=$LATEST" >> $GITHUB_ENV

      - name: Clone death-and-the-flower (with PAT)
        env:
          PAT_FOR_CLONE: ${{ secrets.PAT_FOR_CLONE }}
        run: |
          git clone https://x-access-token:${PAT_FOR_CLONE}@github.com/groovy1985
