name: Trigger Death from Push

on:
  push:
    paths:
      - logs/*.md

jobs:
  post-via-import:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout triggering repo
        uses: actions/checkout@v3

      - name: Clone death-and-the-flower
        run: git clone https://github.com/groovy1985/death-and-the-flower.git

      - name: Find latest log file
        id: get_log
        run: |
          LATEST=$(ls logs | grep '^log.*\.md$' | sort | tail -n 1)
          echo "latest_log=logs/$LATEST" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          cd death-and-the-flower
          pip install -r requirements.txt

      - name: Run death with latest log
        run: |
          cd death-and-the-flower
          python auto_from_external.py \
            --source_file "../${{ env.latest_log }}" \
            --source_type corrupt \
            --persona death
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
