name: Trigger Death from Push

on:
  push:
    branches:
      - main  # 明示的に main ブランチに限定
    paths:
      - logs/**.md  # logs/ 配下すべての .md ファイルを対象

jobs:
  post-via-import:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout triggering repo (Poetic)
        uses: actions/checkout@v3

      - name: Clone death-and-the-flower
        run: git clone https://github.com/groovy1985/death-and-the-flower.git

      - name: Find latest log file
        id: get_log
        run: |
          LATEST=$(ls logs | grep '^log.*\.md$' | sort | tail -n 1)
          echo "latest_log=logs/$LATEST" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          cd death-and-the-flower
          pip install -r requirements.txt

      - name: Run death with latest log
        run: |
          cd death-and-the-flower
          python auto_from_external.py \
            --source_file "../${{ env.latest_log }}" \
            --source_type corrupt \
            --persona dea
